-- SISTEM INFORMASI RT 5
-- ============================================================

-- 1. Tabel Users (Akun Login Pengguna & Admin)
CREATE TABLE IF NOT EXISTS "Users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT UNIQUE,
    "password" TEXT,
    "role" TEXT,
    "nama" TEXT,
    "nik" TEXT
);

-- 2. Tabel Sessions (Token Sesi Login Aktif)
CREATE TABLE IF NOT EXISTS "Sessions" (
    "token" TEXT PRIMARY KEY,
    "nik" TEXT,
    "role" TEXT,
    "createdat" TEXT
);

-- 3. Tabel Warga (Data Kependudukan RT)
CREATE TABLE IF NOT EXISTS "Warga" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_lengkap" TEXT,
    "nama_panggilan" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "jenis_kelamin" TEXT,
    "alamat" TEXT,
    "status_nikah" TEXT,
    "status_tinggal" TEXT,
    "pekerjaan" TEXT,
    "no_hp" TEXT,
    "foto_url" TEXT
);

-- 4. Tabel Iuran (Tagihan & Pembayaran Iuran Warga)
CREATE TABLE IF NOT EXISTS "Iuran" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nik" TEXT,
    "nama" TEXT,
    "no_kk" TEXT,
    "bulan" TEXT,
    "tahun" NUMERIC,
    "nominal" NUMERIC,
    "status" TEXT,
    "tanggal_bayar" TEXT,
    "diterima_oleh" TEXT,
    "bukti_transfer" TEXT
);

-- 5. Tabel Pengaduan (Laporan Aduan Warga)
CREATE TABLE IF NOT EXISTS "Pengaduan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_hp" TEXT,
    "jenis_aduan" TEXT,
    "keterangan" TEXT,
    "tanggal" TEXT,
    "foto_url" TEXT,
    "status" TEXT,
    "foto_penyelesaian" TEXT
);

-- 6. Tabel SuratPengantar (Pengajuan Surat Warga)
CREATE TABLE IF NOT EXISTS "SuratPengantar" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "alamat" TEXT,
    "rt" NUMERIC,
    "jenis_surat" TEXT,
    "status" TEXT,
    "keterangan_admin" TEXT
);

-- 7. Tabel Keuangan (Kas RT Pemasukan & Pengeluaran)
CREATE TABLE IF NOT EXISTS "Keuangan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tanggal" TEXT,
    "pemasukan" NUMERIC,
    "pengeluaran" NUMERIC,
    "keterangan" TEXT,
    "saldo" NUMERIC,
    "foto_url" TEXT
);

-- 8. Tabel Sumbangan (Sumbangan Warga)
CREATE TABLE IF NOT EXISTS "Sumbangan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "tanggal" TEXT,
    "jenis_sumbangan" TEXT,
    "keterangan" TEXT,
    "nominal" NUMERIC,
    "bukti_transfer" TEXT,
    "status" TEXT,
    "nik" TEXT
);

-- 9. Tabel Aset (Inventaris Barang RT)
CREATE TABLE IF NOT EXISTS "Aset" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_barang" TEXT,
    "kondisi" TEXT,
    "jumlah" NUMERIC,
    "status_barang" TEXT
);

-- 10. Tabel Peminjaman (Pinjam Barang RT)
CREATE TABLE IF NOT EXISTS "Peminjaman" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_peminjam" TEXT,
    "id_barang" TEXT,
    "nama_barang" TEXT,
    "jumlah_minta" NUMERIC,
    "acc" NUMERIC,
    "keterangan" TEXT,
    "catatan_rt" TEXT,
    "status" TEXT,
    "tanggal" TEXT,
    "nik" TEXT,
    "jumlah" NUMERIC
);

-- 11. Tabel Aspirasi (Kotak Saran & Masukan Warga)
CREATE TABLE IF NOT EXISTS "Aspirasi" (
    "id" TEXT PRIMARY KEY,
    "tanggal" TEXT,
    "isi_aspirasi" TEXT,
    "status" TEXT,
    "nama" TEXT
);

-- 12. Tabel Kelahiran (Data Kelahiran Warga)
CREATE TABLE IF NOT EXISTS "Kelahiran" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_bayi" TEXT,
    "tanggal_lahir" TEXT,
    "nama_ayah" TEXT,
    "nama_ibu" TEXT,
    "alamat" TEXT,
    "rt" NUMERIC
);

-- 13. Tabel Kematian (Data Kematian Warga)
CREATE TABLE IF NOT EXISTS "Kematian" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "tanggal_meninggal" TEXT,
    "rt" NUMERIC,
    "alamat" TEXT,
    "keterangan" TEXT
);

-- 14. Tabel PindahMasuk (Data Pindah Masuk Warga)
CREATE TABLE IF NOT EXISTS "PindahMasuk" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "asal" TEXT,
    "alamat_baru" TEXT,
    "rt" NUMERIC,
    "tanggal_pindah" TEXT,
    "status_pindah" TEXT
);

-- 15. Tabel PindahKeluar (Data Pindah Keluar Warga)
CREATE TABLE IF NOT EXISTS "PindahKeluar" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "alamat_tujuan" TEXT,
    "rt" NUMERIC,
    "rw" NUMERIC,
    "tanggal_pindah" TEXT
);

-- 16. Tabel Pengaturan (Konfigurasi Aplikasi & Info RT)
CREATE TABLE IF NOT EXISTS "Pengaturan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kunci" TEXT UNIQUE,
    "nilai" TEXT
);

-- ============================================================
-- AKUN ADMIN DEFAULT DATABASE (SAFE INSERT)
-- ============================================================
INSERT INTO "Users" ("username", "password", "role", "nama", "nik") 
SELECT 'adminrt', 'admin123', 'RT', 'Administrator RT', '0'
WHERE NOT EXISTS (SELECT 1 FROM "Users" WHERE "username" = 'adminrt');

-- ============================================================
-- OTOMATISASI PENGATURAN RLS & POLICY UNTUK ANONYMOUS KEY
-- ============================================================
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('DROP POLICY IF EXISTS "Public Access Policy" ON public.%I;', t);
        EXECUTE format('CREATE POLICY "Public Access Policy" ON public.%I FOR ALL USING (true) WITH CHECK (true);', t);
    END LOOP;
END $$;

-- ============================================================
-- SELESAI: SELURUH 16 TABEL DAN RLS TERPERBARUI
-- ============================================================
